apiVersion: v1
kind: Service
metadata:
  name: {{ include "iceberg-rest.fullname" . }}
  labels:
    {{- include "iceberg-rest.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: rest
      port: {{ .Values.service.port }}
      targetPort: rest
  selector:
    {{- include "iceberg-rest.selectorLabels" . | nindent 4 }}
