apiVersion: v1
kind: Service
metadata:
  name: {{ include "knox.fullname" . }}
  labels:
    {{- include "knox.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: gateway
      port: {{ .Values.service.port }}
      targetPort: gateway
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "knox.selectorLabels" . | nindent 4 }}
